# Generated by Django 6.0 on 2026-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_alter_project_options_alter_project_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descriptions',
            field=models.TextField(help_text='Descripción detallada del proyecto', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Imagen de portada del proyecto', upload_to='Proyecto', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(help_text='URL del proyecto o demostración', max_length=150, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Título del proyecto', max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
