# Generated by Django 6.0 on 2026-05-01 17:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_alter_project_created_alter_project_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
