# Generated by Django 6.0 on 2026-05-01 17:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0004_foto_remove_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, help_text='Imagen de portada del proyecto', max_length=255, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
